name: .NET Core

on:
   push:
    branches:
    - master

jobs:
  linux:      
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Build
        run: dotnet build './src/DeepClone/DeepClone.csproj' --configuration Release
      - name: Test
        run: dotnet test './test/DeepCloneUT'
        
  windows:
      runs-on: windows-latest
      steps:
       - name : CheckOut Code
         uses: actions/checkout@v1
      
       - name: Setup DotNet 3.1.100
         uses: actions/setup-dotnet@v1
         with:
             dotnet-version: 3.1.100
       
       - name: Setup DotNet 2.1.4
         uses: actions/setup-dotnet@v1
         with:
             dotnet-version: 2.1.4
       
       - name: Setup Opencover
         uses: crazy-max/ghaction-chocolatey@v1
         with:
             args: install opencover.portable
             env: Setup DotNet 2.1.4
       
       - name: Setup Cover
         uses: crazy-max/ghaction-chocolatey@v1
         with: 
            args: install codecov
     
       - name: Build
         run: dotnet build './src/DeepClone/DeepClone.csproj' --configuration Release
         
       - name: Test
         run: 
             OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test ./test/DeepCloneUT" -output:"./coverage.xml" -oldstyle
       
       - name: Upload Report
         run:
            codecov -f "./coverage.xml" -t ${{ secrets.COVERAGE_KEY }}
   
  mac:
      runs-on: macos
      steps:
      - uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Build
        run: dotnet build './src/DeepClone/DeepClone.csproj' --configuration Release
      - name: Test
        run: dotnet test './test/DeepCloneUT'
